version: '3.8'

services:
  # 1. The Database Service
  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=foodredistribution
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - food_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  # 2. Elasticsearch Service
  elasticsearch:
    image: elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - food_network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 120

  # 3. The Backend Service
  backend:
    build:
      context: ./foodredistribution
    ports:
      - "8080:8080"
    environment:
      # Notice how we use the name of the database service ("database") as the host!
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/foodredistribution
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    volumes:
      # This maps your local Windows 'uploads' folder directly into the container!
      - ./foodredistribution/uploads:/app/uploads
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - food_network

  # 4. The Frontend Service
  frontend:
    build:
      context: ./frontend
    ports:
      # Map localhost:80 (standard HTTP) to container port 80 (Nginx)
      - "80:80"
    depends_on:
      - backend
    networks:
      - food_network

# This creates a persistent volume on your host machine to save database data permanently
volumes:
  db_data:
  es_data:

# This creates a private Wi-Fi network for the containers to talk to each other
networks:
  food_network:
